name: release

on:
  push:
    tags:
      - '*-beta.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Compile
        run: npm run build

      - name: Publish
        run: |
          cd dist 
          npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
